/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controladores.ControladorCitaMedica;
import ec.edu.ups.controladores.ControladorCitaMedicaDetallada;
import ec.edu.ups.controladores.ControladorMedicina;
import ec.edu.ups.controladores.ControladorMedico;
import ec.edu.ups.controladores.ControladorPaciente;
import ec.edu.ups.controladores.ControladorReceta;
import ec.edu.ups.vista.citaMedica.VentanaBuscarCitaMedica;
import ec.edu.ups.vista.citaMedica.VentanaCrearCitaMedica;
import ec.edu.ups.vista.citaMedica.VentanaEliminarCitaMedica;
import ec.edu.ups.vista.citaMedica.VentanaListarCitaMedica;
import ec.edu.ups.vista.medicina.VentanaActualizarMedicina;
import ec.edu.ups.vista.medicina.VentanaBuscarMedicina;
import ec.edu.ups.vista.medicina.VentanaCrearMedicina;
import ec.edu.ups.vista.medicina.VentanaEliminarMedicina;
import ec.edu.ups.vista.medicina.VentanaListarMedicina;
import ec.edu.ups.vista.medico.VentanaActualizarMedico;
import ec.edu.ups.vista.medico.VentanaBuscarMedico;
import ec.edu.ups.vista.medico.VentanaCrearMedico;
import ec.edu.ups.vista.medico.VentanaEliminarMedico;
import ec.edu.ups.vista.medico.VentanaListarMedico;
import ec.edu.ups.vista.paciente.VentanaActualizarPaciente;
import ec.edu.ups.vista.paciente.VentanaBuscaPaciente;
import ec.edu.ups.vista.paciente.VentanaCrearPaciente;
import ec.edu.ups.vista.paciente.VentanaEliminarPaciente;
import ec.edu.ups.vista.paciente.VentanaListarPaciente;
import ec.edu.ups.vista.receta.VentanaCrearReceta;
import java.util.ResourceBundle;
import java.util.Locale;
/**
 *
 * @author Fernanda
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaCrearPaciente ventanaCrearPaciente;
    private VentanaBuscaPaciente ventanaBuscarPaciente;
    private VentanaActualizarPaciente ventanaActualizarPaciente;
    private VentanaEliminarPaciente ventanaEliminarPaciente;
    private VentanaListarPaciente ventanaListarPaciente;
    private VentanaCrearMedico ventanaCrearMedico;
    private VentanaBuscarMedico ventanaBuscarMedico;
    private VentanaActualizarMedico ventanaActualizarMedico;
    private VentanaEliminarMedico ventanaEliminarMedico;
    private VentanaListarMedico ventanaListarMedico;
    private ControladorPaciente controladorPaciente;
    private ControladorMedico controladorMedico;
    private ControladorCitaMedica controladorCitaMedica;
    private ControladorCitaMedicaDetallada controladorCitaMedicaDetallada;
    private VentanaCrearCitaMedica ventanaCrearCitaMedica;
    private VentanaBuscarCitaMedica ventanaBuscarCitaMedica;
    private VentanaEliminarCitaMedica ventanaEliminarCitaMedica;
    private VentanaListarCitaMedica ventanaListarCitaMedica;
    private VentanaCrearMedicina ventanaCrearMedicina;
    private VentanaBuscarMedicina ventanaBuscarMedicina;
    private VentanaActualizarMedicina ventanaActualizarMedicina;
    private VentanaEliminarMedicina ventanaEliminarMedicina;
    private VentanaListarMedicina ventanaListarMedicina;
    private ControladorMedicina controladorMedicina;
    private ControladorReceta controladorReceta;
    private VentanaCrearReceta ventanaCrearReceta;
    private Locale localizacion;
    private ResourceBundle mensajes;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        controladorMedico = new ControladorMedico();
        controladorPaciente = new ControladorPaciente();
        controladorCitaMedica=new ControladorCitaMedica();
        controladorCitaMedicaDetallada=new ControladorCitaMedicaDetallada();
        controladorMedicina = new ControladorMedicina();
        controladorReceta = new ControladorReceta();
        localizacion = new Locale("es","EC");
        Locale.setDefault(localizacion);
        //cambiarIdioma();
    }
    
    public void cambiarIdioma(){
        mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes", Locale.getDefault());
        pacienteMenu.setText(mensajes.getString("menu.paciente"));
        medicoMenu.setText(mensajes.getString("menu.medico"));
        medicinaMenu.setText(mensajes.getString("medicina"));
        citamedicaMenu.setText(mensajes.getString("ecnabezado.citamedica"));
        recetaMenu.setText(mensajes.getString("receta"));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        pacienteMenu = new javax.swing.JMenu();
        crearPaciente = new javax.swing.JMenuItem();
        buscarPaciente = new javax.swing.JMenuItem();
        actualizarPaciente = new javax.swing.JMenuItem();
        listarPaciente = new javax.swing.JMenuItem();
        eliminarPaciente = new javax.swing.JMenuItem();
        medicoMenu = new javax.swing.JMenu();
        crearMedico = new javax.swing.JMenuItem();
        buscarMedico = new javax.swing.JMenuItem();
        actualizarMedico = new javax.swing.JMenuItem();
        listarMedico = new javax.swing.JMenuItem();
        eliminarMedico = new javax.swing.JMenuItem();
        medicinaMenu = new javax.swing.JMenu();
        crearMedicina = new javax.swing.JMenuItem();
        buscarMedicina = new javax.swing.JMenuItem();
        actualizarMedicina = new javax.swing.JMenuItem();
        listarMedicina = new javax.swing.JMenuItem();
        eliminarMedicina = new javax.swing.JMenuItem();
        citamedicaMenu = new javax.swing.JMenu();
        crearCitaMedica = new javax.swing.JMenuItem();
        buscarCitaMedica = new javax.swing.JMenuItem();
        eliminarCitaMedica = new javax.swing.JMenuItem();
        listarCitaMedica = new javax.swing.JMenuItem();
        recetaMenu = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        aboutMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        recetaMenu1 = new javax.swing.JMenu();
        espanol = new javax.swing.JMenuItem();
        ingles = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("jMenu4");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setBorder(null);
        menuBar.setForeground(new java.awt.Color(153, 102, 255));

        pacienteMenu.setMnemonic('f');
        pacienteMenu.setText("PACIENTE");

        crearPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        crearPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuCrear.png"))); // NOI18N
        crearPaciente.setMnemonic('o');
        crearPaciente.setText("CREAR");
        crearPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPacienteActionPerformed(evt);
            }
        });
        pacienteMenu.add(crearPaciente);

        buscarPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        buscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuBuscar.png"))); // NOI18N
        buscarPaciente.setMnemonic('s');
        buscarPaciente.setText("BUSCAR");
        buscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPacienteActionPerformed(evt);
            }
        });
        pacienteMenu.add(buscarPaciente);

        actualizarPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        actualizarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuActualizar.png"))); // NOI18N
        actualizarPaciente.setMnemonic('a');
        actualizarPaciente.setText("ACTUALIZAR");
        actualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPacienteActionPerformed(evt);
            }
        });
        pacienteMenu.add(actualizarPaciente);

        listarPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        listarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuListar.png"))); // NOI18N
        listarPaciente.setMnemonic('x');
        listarPaciente.setText("LISTAR");
        listarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPacienteActionPerformed(evt);
            }
        });
        pacienteMenu.add(listarPaciente);

        eliminarPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        eliminarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuEliminar.png"))); // NOI18N
        eliminarPaciente.setMnemonic('x');
        eliminarPaciente.setText("ELIMINAR");
        eliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPacienteActionPerformed(evt);
            }
        });
        pacienteMenu.add(eliminarPaciente);

        menuBar.add(pacienteMenu);

        medicoMenu.setMnemonic('e');
        medicoMenu.setText("MEDICO");

        crearMedico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        crearMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuCrear.png"))); // NOI18N
        crearMedico.setMnemonic('t');
        crearMedico.setText("CREAR");
        crearMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearMedicoActionPerformed(evt);
            }
        });
        medicoMenu.add(crearMedico);

        buscarMedico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        buscarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuBuscar.png"))); // NOI18N
        buscarMedico.setMnemonic('y');
        buscarMedico.setText("BUSCAR");
        buscarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMedicoActionPerformed(evt);
            }
        });
        medicoMenu.add(buscarMedico);

        actualizarMedico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        actualizarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuActualizar.png"))); // NOI18N
        actualizarMedico.setMnemonic('p');
        actualizarMedico.setText("ACTUALIZAR");
        actualizarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarMedicoActionPerformed(evt);
            }
        });
        medicoMenu.add(actualizarMedico);

        listarMedico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        listarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuListar.png"))); // NOI18N
        listarMedico.setMnemonic('d');
        listarMedico.setText("LISTAR");
        listarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMedicoActionPerformed(evt);
            }
        });
        medicoMenu.add(listarMedico);

        eliminarMedico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        eliminarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuEliminar.png"))); // NOI18N
        eliminarMedico.setMnemonic('d');
        eliminarMedico.setText("ELIMINAR");
        eliminarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMedicoActionPerformed(evt);
            }
        });
        medicoMenu.add(eliminarMedico);

        menuBar.add(medicoMenu);

        medicinaMenu.setMnemonic('h');
        medicinaMenu.setText("MEDICINA");

        crearMedicina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        crearMedicina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuCrear.png"))); // NOI18N
        crearMedicina.setMnemonic('c');
        crearMedicina.setText("CREAR");
        crearMedicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearMedicinaActionPerformed(evt);
            }
        });
        medicinaMenu.add(crearMedicina);

        buscarMedicina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        buscarMedicina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuBuscar.png"))); // NOI18N
        buscarMedicina.setMnemonic('a');
        buscarMedicina.setText("BUSCAR");
        buscarMedicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMedicinaActionPerformed(evt);
            }
        });
        medicinaMenu.add(buscarMedicina);

        actualizarMedicina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        actualizarMedicina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuActualizar.png"))); // NOI18N
        actualizarMedicina.setMnemonic('a');
        actualizarMedicina.setText("ACTUALIZAR");
        actualizarMedicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarMedicinaActionPerformed(evt);
            }
        });
        medicinaMenu.add(actualizarMedicina);

        listarMedicina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        listarMedicina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuListar.png"))); // NOI18N
        listarMedicina.setMnemonic('a');
        listarMedicina.setText("LISTAR");
        listarMedicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMedicinaActionPerformed(evt);
            }
        });
        medicinaMenu.add(listarMedicina);

        eliminarMedicina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        eliminarMedicina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuEliminar.png"))); // NOI18N
        eliminarMedicina.setMnemonic('a');
        eliminarMedicina.setText("ELIMINAR");
        eliminarMedicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMedicinaActionPerformed(evt);
            }
        });
        medicinaMenu.add(eliminarMedicina);

        menuBar.add(medicinaMenu);

        citamedicaMenu.setText("CITA MEDICA");

        crearCitaMedica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuCrear.png"))); // NOI18N
        crearCitaMedica.setText("CREAR");
        crearCitaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCitaMedicaActionPerformed(evt);
            }
        });
        citamedicaMenu.add(crearCitaMedica);

        buscarCitaMedica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuBuscar.png"))); // NOI18N
        buscarCitaMedica.setText("BUSCAR");
        buscarCitaMedica.setToolTipText("");
        buscarCitaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCitaMedicaActionPerformed(evt);
            }
        });
        citamedicaMenu.add(buscarCitaMedica);

        eliminarCitaMedica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuEliminar.png"))); // NOI18N
        eliminarCitaMedica.setText("ELIMINAR");
        eliminarCitaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCitaMedicaActionPerformed(evt);
            }
        });
        citamedicaMenu.add(eliminarCitaMedica);

        listarCitaMedica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuListar.png"))); // NOI18N
        listarCitaMedica.setText("LISTAR");
        listarCitaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCitaMedicaActionPerformed(evt);
            }
        });
        citamedicaMenu.add(listarCitaMedica);

        menuBar.add(citamedicaMenu);

        recetaMenu.setText("RECETA");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuCrear.png"))); // NOI18N
        jMenuItem5.setText("CREAR");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        recetaMenu.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuBuscar.png"))); // NOI18N
        jMenuItem6.setText("BUSCAR");
        jMenuItem6.setToolTipText("");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        recetaMenu.add(jMenuItem6);

        aboutMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuActualizar.png"))); // NOI18N
        aboutMenuItem4.setMnemonic('a');
        aboutMenuItem4.setText("ACTUALIZAR");
        aboutMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem4ActionPerformed(evt);
            }
        });
        recetaMenu.add(aboutMenuItem4);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuListar.png"))); // NOI18N
        jMenuItem8.setText("LISTAR");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        recetaMenu.add(jMenuItem8);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuEliminar.png"))); // NOI18N
        jMenuItem7.setText("ELIMINAR");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        recetaMenu.add(jMenuItem7);

        menuBar.add(recetaMenu);

        recetaMenu1.setText("RECETA");

        espanol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuIdioma.png"))); // NOI18N
        espanol.setText("ESPAÑOL");
        espanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espanolActionPerformed(evt);
            }
        });
        recetaMenu1.add(espanol);

        ingles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/BotonMenuIdioma.png"))); // NOI18N
        ingles.setText("INGLES");
        ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inglesActionPerformed(evt);
            }
        });
        recetaMenu1.add(ingles);

        menuBar.add(recetaMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPacienteActionPerformed
    if(ventanaListarPaciente == null || !ventanaListarPaciente.isVisible()){
        ventanaListarPaciente=new VentanaListarPaciente(controladorPaciente);
        ventanaListarPaciente.setVisible(true);
        desktopPane.add(ventanaListarPaciente);
       }
    }//GEN-LAST:event_listarPacienteActionPerformed

    private void buscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPacienteActionPerformed
          if(ventanaBuscarPaciente == null || !ventanaBuscarPaciente.isVisible()){
        ventanaBuscarPaciente=new VentanaBuscaPaciente(controladorPaciente);
        ventanaBuscarPaciente.setVisible(true);
        desktopPane.add(ventanaBuscarPaciente);
       } 
    }//GEN-LAST:event_buscarPacienteActionPerformed

    private void eliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPacienteActionPerformed
        if(ventanaEliminarPaciente == null || !ventanaEliminarPaciente.isVisible()){
        ventanaEliminarPaciente=new VentanaEliminarPaciente(controladorPaciente);
        ventanaEliminarPaciente.setVisible(true);
        desktopPane.add(ventanaEliminarPaciente);
       }
    }//GEN-LAST:event_eliminarPacienteActionPerformed

    private void crearMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearMedicoActionPerformed
        // TODO add your handling code here:
        if(ventanaCrearMedico == null || !ventanaCrearMedico.isVisible()){
        ventanaCrearMedico = new VentanaCrearMedico(controladorMedico);
        ventanaCrearMedico.setVisible(true);
        desktopPane.add(ventanaCrearMedico);
        }
    }//GEN-LAST:event_crearMedicoActionPerformed

    private void crearPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPacienteActionPerformed
        // TODO add your handling code here:
      if(ventanaCrearPaciente == null || !ventanaCrearPaciente.isVisible()){
        ventanaCrearPaciente = new VentanaCrearPaciente(controladorPaciente);
        ventanaCrearPaciente.setVisible(true);
        desktopPane.add(ventanaCrearPaciente);
        }
    }//GEN-LAST:event_crearPacienteActionPerformed

    private void buscarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMedicoActionPerformed
      if(ventanaBuscarMedico == null || !ventanaBuscarMedico.isVisible()){
        ventanaBuscarMedico = new VentanaBuscarMedico(controladorMedico);
        ventanaBuscarMedico.setVisible(true);
        desktopPane.add(ventanaBuscarMedico);
        }
    }//GEN-LAST:event_buscarMedicoActionPerformed

    private void actualizarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarMedicoActionPerformed
        if(ventanaActualizarMedico == null || !ventanaActualizarMedico.isVisible()){
        ventanaActualizarMedico = new VentanaActualizarMedico(controladorMedico);
        ventanaActualizarMedico.setVisible(true);
        desktopPane.add(ventanaActualizarMedico);
        }
    }//GEN-LAST:event_actualizarMedicoActionPerformed

    private void eliminarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMedicoActionPerformed
      if(ventanaEliminarMedico == null || !ventanaEliminarMedico.isVisible()){
        ventanaEliminarMedico = new VentanaEliminarMedico(controladorMedico);
        ventanaEliminarMedico.setVisible(true);
        desktopPane.add(ventanaEliminarMedico);
        }
    }//GEN-LAST:event_eliminarMedicoActionPerformed

    private void listarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMedicoActionPerformed
       if(ventanaListarMedico == null || !ventanaListarMedico.isVisible()){
        ventanaListarMedico = new VentanaListarMedico(controladorMedico);
        ventanaListarMedico.setVisible(true);
        desktopPane.add(ventanaListarMedico);
        }
    }//GEN-LAST:event_listarMedicoActionPerformed

    private void crearMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearMedicinaActionPerformed
       if(ventanaCrearMedicina == null || !ventanaCrearMedicina.isVisible()){
        ventanaCrearMedicina = new VentanaCrearMedicina(controladorMedicina);
        ventanaCrearMedicina.setVisible(true);
        desktopPane.add(ventanaCrearMedicina);
        }
    }//GEN-LAST:event_crearMedicinaActionPerformed

    private void eliminarMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMedicinaActionPerformed
        if(ventanaEliminarMedicina== null || !ventanaEliminarMedicina.isVisible()){
          ventanaEliminarMedicina = new VentanaEliminarMedicina(controladorMedicina);
        ventanaEliminarMedicina.setVisible(true);
        desktopPane.add(ventanaEliminarMedicina);
        }
    }//GEN-LAST:event_eliminarMedicinaActionPerformed

    private void buscarMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMedicinaActionPerformed
        if(ventanaBuscarMedicina == null || !ventanaBuscarMedicina.isVisible()){
        ventanaBuscarMedicina = new VentanaBuscarMedicina(controladorMedicina);
        ventanaBuscarMedicina.setVisible(true);
        desktopPane.add(ventanaBuscarMedicina);
        }
    }//GEN-LAST:event_buscarMedicinaActionPerformed

    private void actualizarMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarMedicinaActionPerformed
         if(ventanaActualizarMedicina== null || !ventanaActualizarMedicina.isVisible()){
         ventanaActualizarMedicina = new VentanaActualizarMedicina(controladorMedicina);
        ventanaActualizarMedicina.setVisible(true);
        desktopPane.add(ventanaActualizarMedicina);
        }
    }//GEN-LAST:event_actualizarMedicinaActionPerformed

    private void listarMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMedicinaActionPerformed
        if(ventanaListarMedicina == null || !ventanaListarMedicina.isVisible()){
        ventanaListarMedicina = new VentanaListarMedicina(controladorMedicina);
        ventanaListarMedicina.setVisible(true);
        desktopPane.add(ventanaListarMedicina);
        }
    }//GEN-LAST:event_listarMedicinaActionPerformed

    private void crearCitaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCitaMedicaActionPerformed
        // TODO add your handling code here:
          if(ventanaCrearCitaMedica == null || !ventanaCrearCitaMedica.isVisible()){
        ventanaCrearCitaMedica = new VentanaCrearCitaMedica(controladorCitaMedica, controladorCitaMedicaDetallada, controladorPaciente, controladorMedico);
        ventanaCrearCitaMedica.setVisible(true);
        desktopPane.add(ventanaCrearCitaMedica);
        }
    }//GEN-LAST:event_crearCitaMedicaActionPerformed

    private void listarCitaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCitaMedicaActionPerformed
        // TODO add your handling code here:
          if(ventanaListarCitaMedica== null || !ventanaListarCitaMedica.isVisible()){
        ventanaListarCitaMedica=new VentanaListarCitaMedica(controladorCitaMedica, controladorCitaMedicaDetallada, controladorMedico, controladorPaciente);
        ventanaListarCitaMedica.setVisible(true);
        desktopPane.add(ventanaListarCitaMedica);
       }
    }//GEN-LAST:event_listarCitaMedicaActionPerformed

    private void buscarCitaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCitaMedicaActionPerformed
           if(ventanaBuscarCitaMedica == null || !ventanaBuscarCitaMedica.isVisible()){
        ventanaBuscarCitaMedica=new VentanaBuscarCitaMedica(controladorCitaMedica, controladorCitaMedicaDetallada, controladorPaciente, controladorMedico);
        ventanaBuscarCitaMedica.setVisible(true);
        desktopPane.add(ventanaBuscarCitaMedica);
       }
    }//GEN-LAST:event_buscarCitaMedicaActionPerformed

    private void eliminarCitaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCitaMedicaActionPerformed
          if(ventanaEliminarCitaMedica == null || !ventanaEliminarCitaMedica.isVisible()){
        ventanaEliminarCitaMedica=new VentanaEliminarCitaMedica(controladorCitaMedica);
        ventanaEliminarCitaMedica.setVisible(true);
        desktopPane.add(ventanaEliminarCitaMedica);
       }
    }//GEN-LAST:event_eliminarCitaMedicaActionPerformed

    private void actualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPacienteActionPerformed
          if(ventanaActualizarPaciente == null || !ventanaActualizarPaciente.isVisible()){
        ventanaActualizarPaciente=new VentanaActualizarPaciente(controladorPaciente);
        ventanaActualizarPaciente.setVisible(true);
        desktopPane.add(ventanaActualizarPaciente);
       }
    }//GEN-LAST:event_actualizarPacienteActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       if(ventanaCrearReceta == null || !ventanaCrearReceta.isVisible()){
        ventanaCrearReceta = new VentanaCrearReceta(controladorReceta, controladorCitaMedica, controladorPaciente);
        ventanaCrearReceta.setVisible(true);
        desktopPane.add(ventanaCrearReceta);
        }
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void aboutMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItem4ActionPerformed

    private void espanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espanolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espanolActionPerformed

    private void inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inglesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem4;
    private javax.swing.JMenuItem actualizarMedicina;
    private javax.swing.JMenuItem actualizarMedico;
    private javax.swing.JMenuItem actualizarPaciente;
    private javax.swing.JMenuItem buscarCitaMedica;
    private javax.swing.JMenuItem buscarMedicina;
    private javax.swing.JMenuItem buscarMedico;
    private javax.swing.JMenuItem buscarPaciente;
    private javax.swing.JMenu citamedicaMenu;
    private javax.swing.JMenuItem crearCitaMedica;
    private javax.swing.JMenuItem crearMedicina;
    private javax.swing.JMenuItem crearMedico;
    private javax.swing.JMenuItem crearPaciente;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem eliminarCitaMedica;
    private javax.swing.JMenuItem eliminarMedicina;
    private javax.swing.JMenuItem eliminarMedico;
    private javax.swing.JMenuItem eliminarPaciente;
    private javax.swing.JMenuItem espanol;
    private javax.swing.JMenuItem ingles;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem listarCitaMedica;
    private javax.swing.JMenuItem listarMedicina;
    private javax.swing.JMenuItem listarMedico;
    private javax.swing.JMenuItem listarPaciente;
    private javax.swing.JMenu medicinaMenu;
    private javax.swing.JMenu medicoMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu pacienteMenu;
    private javax.swing.JMenu recetaMenu;
    private javax.swing.JMenu recetaMenu1;
    // End of variables declaration//GEN-END:variables

}
